version: '3'
services:
    app:
        # 起動イメージ
        image: node:18
        # 環境変数
        environment:
            - DEBUG=app:*
        tty: true
        # ホスト側のポート：コンテナのポート
        ports:
            - '3000:3000'
        # ホスト側のsrcをコンテナのappにマウント
        volumes:
            - ./src:/app
        # 起動時のカレントフォルダ
        working_dir: /app
        # 起動後に実行するコマンド
        command: sh -c 'npx tsc; npm run dev'
    my_mysql:
        image: mysql #もととなるイメージ。ここではmysql
        environment: #最小限の記述にしています。他にも環境設定は可能です。
            MYSQL_ROOT_PASSWORD: root #rootパスワード。今回はrootにしました。
            MYSQL_DATABASE: my_mysql_db #作成するデータベース。今回はmy_mysql_dbにしました。
        ports:
            - '3300:3300' #接続するポート番号。お好きな番号でいけます。
        volumes:
            - my_volume:/var/lib/mysql　    #第３の場所my_volumeをコンテナ内に同期するコード
    redis:
        image: "redis:latest"
        ports:
            - "6379:6379"
        volumes:
             - redis_volume:/data/redis:/data
volumes:
    my_volume:
    redis_volume:


